#training.yaml
epochs: 10
batch_size: 8
learning_rate: 5e-5
do_train: True
do_eval: True
overwrite_output_dir: True
evaluation_strategy: "epoch"
save_strategy: "epoch"
load_best_model_at_end: True
metric_for_best_model: "eval_accuracy"