#training.yaml
epochs: 4
batch_size: 8
learning_rate: 1e-4
do_train: True
do_eval: True
overwrite_output_dir: True
evaluation_strategy: "step"
save_strategy: "step"
load_best_model_at_end: True
metric_for_best_model: "eval_accuracy"